#!/usr/bin/env bash
# script tranfers file from one client to a server

# Function to display usage
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if less than 4 parameters are passed
if [ "$#" -ne 4 ]; then
    usage
fi

# Assign parameters to variables
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfer the file using scp
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"

# Check if scp was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
