#!/usr/bin/env bash
# script configure new ubuntu with custom http header
# shellcheck disable=SC2154

# Update package lists and install Nginx
sudo apt update
sudo apt install -y nginx

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Add custom header to Nginx configuration
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name memesoft.tech;

    # My custom header
    add_header X-Served-By "hostname";

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF'

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

echo "Nginx has been configured with the custom header."
