#!/usr/bin/env bash
# This script displays a list of all the current running processes
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest --no-headers
