#!/usr/bin/env bash
# This script displays numbers from 1 to 100
#
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number in a list format
num=1
while [ $num -le 100 ]; do
	if [ $((num % 3)) -eq 0 ] && [ $((num % 5)) -ne 0 ]; then
		echo "Fizz"
	elif [ $((num % 5)) -eq 0 ] && [ $((num % 3)) -ne 0 ]; then
		echo "Buzz"
	elif [ $((num % 3)) -eq 0 ] && [ $((num % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	else
		echo $num
	fi
	((num++));
done
