#!/usr/bin/env bash
# This script displays "Best School" 10 times, but "Best school" and "Hi" on 9th iteration
i=0
while [ $i -lt 10 ]; do
	echo "Best School"
	if [ $i -eq 8 ]; then
		echo "Hi"
	fi
	((i++));
done
