#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes
hour=0
min=1
while [ $hour -le 12 ]; do
	min=1
	echo "Hour:" $hour
	while [ $min -lt 60 ]; do
		echo $min
		((min++));
	done
	((hour++));
done
